Repository codesquad-member-2020/todo-1, pull requests merged in 2020-04, with the labels that each got.

#2 프로젝트 생성 및 설정
  client-mobile/.gitignore
  client-mobile/README.md
  client-mobile/ToDoListApp/ToDoListApp.xcodeproj/project.pbxproj
  client-mobile/ToDoListApp/ToDoListApp.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  client-mobile/ToDoListApp/ToDoListApp.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  client-mobile/ToDoListApp/ToDoListApp/AppDelegate.swift
  client-mobile/ToDoListApp/ToDoListApp/Assets.xcassets/AppIcon.appiconset/Contents.json
  client-mobile/ToDoListApp/ToDoListApp/Assets.xcassets/Contents.json
  client-mobile/ToDoListApp/ToDoListApp/Base.lproj/LaunchScreen.storyboard
  client-mobile/ToDoListApp/ToDoListApp/Base.lproj/Main.storyboard
  client-mobile/ToDoListApp/ToDoListApp/Info.plist
  client-mobile/ToDoListApp/ToDoListApp/SceneDelegate.swift
  client-mobile/ToDoListApp/ToDoListApp/ViewController.swift
Labels: documentation, iOS

#4 ToDoViewController UI 구현
  client-mobile/ToDoListApp/ToDoListApp.xcodeproj/project.pbxproj
  client-mobile/ToDoListApp/ToDoListApp/Base.lproj/Main.storyboard
  client-mobile/ToDoListApp/ToDoListApp/ViewController.swift
  client-mobile/ToDoListApp/ToDoListApp/ViewControllers/CardListViewController.swift
  client-mobile/ToDoListApp/ToDoListApp/ViewControllers/ToDoListViewController.swift
Labels: enhancement, iOS

#8 카드리스트 tableview UI 구현
  client-mobile/ToDoListApp/ToDoListApp.xcodeproj/project.pbxproj
  client-mobile/ToDoListApp/ToDoListApp/Assets.xcassets/cardListBackGroundColor.colorset/Contents.json
  client-mobile/ToDoListApp/ToDoListApp/Base.lproj/Main.storyboard
  client-mobile/ToDoListApp/ToDoListApp/Models/DoneCardListDataSource.swift
  client-mobile/ToDoListApp/ToDoListApp/Models/InProgressCardListDataSource.swift
  client-mobile/ToDoListApp/ToDoListApp/Models/ToDoCardListDataSource.swift
  client-mobile/ToDoListApp/ToDoListApp/ViewControllers/ToDoListViewController.swift
  client-mobile/ToDoListApp/ToDoListApp/Views/CardCell.swift
  client-mobile/ToDoListApp/ToDoListApp/Views/DoneCardListDelegate.swift
  client-mobile/ToDoListApp/ToDoListApp/Views/InProgressCardListDelegate.swift
  client-mobile/ToDoListApp/ToDoListApp/Views/ToDoBedgeView.swift
  client-mobile/ToDoListApp/ToDoListApp/Views/ToDoCardListDelegate.swift
Labels: enhancement, iOS

#11 [FE] webpack 설정 완료
  FE/.gitignore
  FE/config/webpack.config.dev.js
  FE/config/webpack.config.prod.js
  FE/package.json
  FE/src/js/main.js
  FE/src/login.html
  FE/src/scss/config/_variables.scss
  FE/src/scss/config/reset.scss
  FE/src/scss/main.scss
  FE/src/scss/styles.scss
Labels: FE

#14 CardList 뷰컨트롤러 구조 변경
  client-mobile/ToDoListApp/ToDoListApp.xcodeproj/project.pbxproj
  client-mobile/ToDoListApp/ToDoListApp/Base.lproj/Main.storyboard
  client-mobile/ToDoListApp/ToDoListApp/Models/CardList/Card.swift
  client-mobile/ToDoListApp/ToDoListApp/Models/CardList/Column.swift
  client-mobile/ToDoListApp/ToDoListApp/Models/DoneCardListDataSource.swift
  client-mobile/ToDoListApp/ToDoListApp/Models/ToDoCardListDataSource.swift
  client-mobile/ToDoListApp/ToDoListApp/ViewControllers/CardListViewController.swift
  client-mobile/ToDoListApp/ToDoListApp/ViewControllers/ToDoListViewController.swift
  client-mobile/ToDoListApp/ToDoListApp/Views/CardCell.swift
  client-mobile/ToDoListApp/ToDoListApp/Views/CardList/BedgeView.swift
  client-mobile/ToDoListApp/ToDoListApp/Views/CardList/CardCell.swift
  client-mobile/ToDoListApp/ToDoListApp/Views/CardList/CardListDataSource.swift
  client-mobile/ToDoListApp/ToDoListApp/Views/CardList/CardListDelegate.swift
  client-mobile/ToDoListApp/ToDoListApp/Views/CardList/ColumnView.swift
  client-mobile/ToDoListApp/ToDoListApp/Views/InProgressCardListDelegate.swift
Labels: enhancement, iOS, refactoring

#15 [FE] login & todo list 화면 HTML/CSS 완료
  FE/package.json
  FE/src/login.html
  FE/src/scss/config/_variables.scss
  FE/src/scss/config/reset.scss
  FE/src/scss/main.scss
  FE/src/scss/pages/login.scss
  FE/src/scss/pages/todo.scss
  FE/src/scss/styles.scss
  FE/src/todo.html
Labels: FE

#22 [FE] webpack config 수정 및 배포용 파일 업데이트
  FE/build/login.bundle.js
  FE/build/login.html
  FE/build/style.css
  FE/build/todo.bundle.js
  FE/build/todo.html
  FE/config/webpack.config.dev.js
  FE/config/webpack.config.prod.js
  FE/package.json
  FE/src/js/login.js
  FE/src/js/todo.js
  FE/src/login.html
  FE/src/todo.html
Labels: FE

#23 [FE] 배포 테스트 요청
  FE/build/login.bundle.js
  FE/build/login.html
  FE/build/style.css
  FE/build/todo.bundle.js
  FE/build/todo.html
  FE/config/webpack.config.dev.js
  FE/config/webpack.config.prod.js
  FE/package.json
  FE/src/js/login.js
  FE/src/js/todo.js
  FE/src/login.html
  FE/src/todo.html
Labels: FE

#27 카드 추가 뷰컨트롤러 구현
  client-mobile/ToDoListApp/ToDoListApp.xcodeproj/project.pbxproj
  client-mobile/ToDoListApp/ToDoListApp/Base.lproj/Main.storyboard
  client-mobile/ToDoListApp/ToDoListApp/ViewControllers/NewCardViewController.swift
  client-mobile/ToDoListApp/ToDoListApp/ViewModels/NewCardViewModel.swift
  client-mobile/ToDoListApp/ToDoListApp/Views/CardContetnsTextViewDelegate.swift
  client-mobile/ToDoListApp/ToDoListApp/Views/CardTitleTextFieldDelegate.swift
Labels: enhancement, iOS

#29 [FE] 코드 구조 설계
  FE/config/webpack.config.dev.js
  FE/config/webpack.config.prod.js
  FE/package.json
  FE/src/js/components/Alert.js
  FE/src/js/components/Card.js
  FE/src/js/components/CardCreator.js
  FE/src/js/components/CardEditor.js
  FE/src/js/components/Column.js
  FE/src/js/components/ColumnContainer.js
  FE/src/js/components/ColumnCreator.js
  FE/src/js/components/Header.js
  FE/src/js/components/History.js
  FE/src/js/components/Todo.js
  FE/src/js/data.js
  FE/src/js/login.js
  FE/src/js/todo.js
  FE/src/scss/pages/todo.scss
  FE/src/todo.html
Labels: FE

#30 [FE] TodoList 화면 렌더링 기능 구현
  FE/src/js/components/Card.js
  FE/src/js/components/Column.js
  FE/src/js/components/ColumnContainer.js
  FE/src/js/components/Header.js
  FE/src/js/data.js
  FE/src/js/utils/template.js
  FE/src/todo.html
Labels: FE

#34 카드리스트에 카드 추가
  client-mobile/ToDoListApp/ToDoListApp.xcodeproj/project.pbxproj
  client-mobile/ToDoListApp/ToDoListApp/Base.lproj/Main.storyboard
  client-mobile/ToDoListApp/ToDoListApp/Models/CardList/Card.swift
  client-mobile/ToDoListApp/ToDoListApp/Models/CardList/Column.swift
  client-mobile/ToDoListApp/ToDoListApp/ViewControllers/CardListViewController.swift
  client-mobile/ToDoListApp/ToDoListApp/ViewControllers/NewCardViewController.swift
  client-mobile/ToDoListApp/ToDoListApp/ViewModels/CardViewModel.swift
  client-mobile/ToDoListApp/ToDoListApp/Views/CardList/CardCell.swift
  client-mobile/ToDoListApp/ToDoListApp/Views/NewCard/CardContetnsTextViewDelegate.swift
  client-mobile/ToDoListApp/ToDoListApp/Views/NewCard/CardTitleTextFieldDelegate.swift
Labels: enhancement, iOS

#41 [FE] 카드 추가 기능 구현
  FE/src/js/components/Card.js
  FE/src/js/components/CardCreator.js
  FE/src/js/components/Column.js
  FE/src/js/components/ColumnContainer.js
  FE/src/js/data.js
  FE/src/js/utils/template.js
  FE/src/scss/config/_variables.scss
  FE/src/scss/config/reset.scss
  FE/src/scss/main.scss
  FE/src/scss/pages/login.scss
  FE/src/scss/pages/todo.scss
Labels: FE

#42 [FE] 카드 삭제 기능 구현
  FE/src/js/components/Card.js
  FE/src/js/components/Column.js
  FE/src/js/utils/template.js
  FE/src/scss/partials/alert.scss
  FE/src/scss/styles.scss
Labels: FE

#44 [FE] 카드 삭제시 얼럿창 노출 기능 추가
  FE/src/js/components/Alert.js
  FE/src/js/components/Card.js
  FE/src/js/components/ColumnContainer.js
  FE/src/js/utils/template.js
Labels: FE

#46 [#45] bugfix Json 구조 변경
  BE/src/main/java/com/codesquad/todo1/api/ApiShowList.java
  BE/src/main/java/com/codesquad/todo1/controller/TodoController.java
Labels: BE, bug

#47 ViewModel로 로직 처리 변경 및 네트워크 처리
  client-mobile/ToDoListApp/ToDoListApp.xcodeproj/project.pbxproj
  client-mobile/ToDoListApp/ToDoListApp/Base.lproj/Main.storyboard
  client-mobile/ToDoListApp/ToDoListApp/Models/CardList/Card.swift
  client-mobile/ToDoListApp/ToDoListApp/Models/CardList/Column.swift
  client-mobile/ToDoListApp/ToDoListApp/Models/NetworkManager.swift
  client-mobile/ToDoListApp/ToDoListApp/Models/UserData.swift
  client-mobile/ToDoListApp/ToDoListApp/ViewControllers/ColumnViewController.swift
  client-mobile/ToDoListApp/ToDoListApp/ViewControllers/NewCardViewController.swift
  client-mobile/ToDoListApp/ToDoListApp/ViewControllers/ToDoListViewController.swift
  client-mobile/ToDoListApp/ToDoListApp/ViewModels/CardViewModel.swift
  client-mobile/ToDoListApp/ToDoListApp/ViewModels/ColumnViewModel.swift
  client-mobile/ToDoListApp/ToDoListApp/ViewModels/NewCard/ContentsViewModel.swift
  client-mobile/ToDoListApp/ToDoListApp/ViewModels/NewCard/TItleViewModel.swift
  client-mobile/ToDoListApp/ToDoListApp/Views/NewCard/CardContentsTextViewDelegate.swift
  client-mobile/ToDoListApp/ToDoListApp/Views/NewCard/CardTitleTextFieldDelegate.swift
Labels: iOS, refactoring

#49 [FE] 카드 수정 기능 구현 완료
  FE/build/login.bundle.js
  FE/build/login.html
  FE/build/style.css
  FE/build/todo.bundle.js
  FE/build/todo.html
  FE/src/js/components/Alert.js
  FE/src/js/components/CardEditor.js
  FE/src/js/components/Column.js
  FE/src/js/components/ColumnContainer.js
  FE/src/js/data.js
  FE/src/js/utils/template.js
  FE/src/scss/pages/todo.scss
  FE/src/scss/partials/cardEditor.scss
  FE/src/scss/styles.scss
Labels: FE

#50 [FE] 1주차 작업본
  FE/build/login.bundle.js
  FE/build/login.html
  FE/build/style.css
  FE/build/todo.bundle.js
  FE/build/todo.html
  FE/config/webpack.config.dev.js
  FE/config/webpack.config.prod.js
  FE/package.json
  FE/src/js/components/Alert.js
  FE/src/js/components/Card.js
  FE/src/js/components/CardCreator.js
  FE/src/js/components/CardEditor.js
  FE/src/js/components/Column.js
  FE/src/js/components/ColumnContainer.js
  FE/src/js/components/ColumnCreator.js
  FE/src/js/components/Header.js
  FE/src/js/components/History.js
  FE/src/js/components/Todo.js
  FE/src/js/data.js
  FE/src/js/login.js
  FE/src/js/todo.js
  FE/src/js/utils/template.js
  FE/src/scss/config/_variables.scss
  FE/src/scss/config/reset.scss
  FE/src/scss/main.scss
  FE/src/scss/pages/login.scss
  FE/src/scss/pages/todo.scss
  FE/src/scss/partials/alert.scss
  FE/src/scss/partials/cardEditor.scss
  FE/src/scss/styles.scss
  FE/src/todo.html
Labels: FE

#51 네트워크 처리 Result type을 사용한 에러 핸들링
  client-mobile/ToDoListApp/ToDoListApp/Models/NetworkManager.swift
  client-mobile/ToDoListApp/ToDoListApp/ViewControllers/ToDoListViewController.swift
Labels: iOS, refactoring

#52 1차 데모
  client-mobile/ToDoListApp/ToDoListApp.xcodeproj/project.pbxproj
  client-mobile/ToDoListApp/ToDoListApp/Assets.xcassets/cardListBackGroundColor.colorset/Contents.json
  client-mobile/ToDoListApp/ToDoListApp/Base.lproj/Main.storyboard
  client-mobile/ToDoListApp/ToDoListApp/Models/CardList/Card.swift
  client-mobile/ToDoListApp/ToDoListApp/Models/CardList/Column.swift
  client-mobile/ToDoListApp/ToDoListApp/Models/NetworkManager.swift
  client-mobile/ToDoListApp/ToDoListApp/Models/UserData.swift
  client-mobile/ToDoListApp/ToDoListApp/ViewControllers/CardListViewController.swift
  client-mobile/ToDoListApp/ToDoListApp/ViewControllers/ColumnViewController.swift
  client-mobile/ToDoListApp/ToDoListApp/ViewControllers/NewCardViewController.swift
  client-mobile/ToDoListApp/ToDoListApp/ViewControllers/ToDoListViewController.swift
  client-mobile/ToDoListApp/ToDoListApp/ViewModels/ColumnViewModel.swift
  client-mobile/ToDoListApp/ToDoListApp/ViewModels/NewCard/ContentsViewModel.swift
  client-mobile/ToDoListApp/ToDoListApp/ViewModels/NewCard/TItleViewModel.swift
  client-mobile/ToDoListApp/ToDoListApp/Views/CardList/BedgeView.swift
  client-mobile/ToDoListApp/ToDoListApp/Views/CardList/CardCell.swift
  client-mobile/ToDoListApp/ToDoListApp/Views/CardList/CardListDataSource.swift
  client-mobile/ToDoListApp/ToDoListApp/Views/CardList/CardListDelegate.swift
  client-mobile/ToDoListApp/ToDoListApp/Views/CardList/ColumnView.swift
  client-mobile/ToDoListApp/ToDoListApp/Views/NewCard/CardContentsTextViewDelegate.swift
  client-mobile/ToDoListApp/ToDoListApp/Views/NewCard/CardTitleTextFieldDelegate.swift
Labels: enhancement, iOS

#57 서버 변경 반영
  client-mobile/ToDoListApp/ToDoListApp/Models/NetworkManager.swift
  client-mobile/ToDoListApp/ToDoListApp/Models/UserData.swift
Labels: hotfix, iOS

#59 [FE] 카드 생성시 타이틀 입력 기능 추가
  FE/src/js/components/CardCreator.js
  FE/src/js/components/Column.js
  FE/src/js/components/ColumnContainer.js
  FE/src/js/data.js
  FE/src/js/utils/template.js
  FE/src/scss/pages/todo.scss
Labels: FE

#60 [FE] 카드 수정 기능 추가 구현
  FE/src/js/components/CardCreator.js
  FE/src/js/components/CardEditor.js
  FE/src/js/components/Column.js
  FE/src/js/components/ColumnContainer.js
  FE/src/js/utils/template.js
  FE/src/scss/config/reset.scss
  FE/src/scss/main.scss
  FE/src/scss/partials/cardEditor.scss
Labels: FE

#63 Columns 요청 URL path 수정
  client-mobile/ToDoListApp/ToDoListApp/Models/NetworkManager.swift
Labels: hotfix, iOS

#65 변경된 Data Key값 반영 및 에러 핸들링
  client-mobile/ToDoListApp/ToDoListApp/Models/CardList/Card.swift
  client-mobile/ToDoListApp/ToDoListApp/Models/CardList/Column.swift
  client-mobile/ToDoListApp/ToDoListApp/ViewControllers/NewCardViewController.swift
  client-mobile/ToDoListApp/ToDoListApp/ViewControllers/ToDoListViewController.swift
Labels: hotfix, iOS

#66 [FE] 드래그 앤 드랍 기능 구현
  FE/src/js/components/Column.js
  FE/src/js/components/ColumnContainer.js
  FE/src/js/data.js
  FE/src/js/utils/template.js
  FE/src/scss/pages/todo.scss
Labels: FE

#67 변경된 하나의 Card만 카드리스트에 반영
  client-mobile/ToDoListApp/ToDoListApp.xcodeproj/project.pbxproj
  client-mobile/ToDoListApp/ToDoListApp/Base.lproj/Main.storyboard
  client-mobile/ToDoListApp/ToDoListApp/Models/CardList/Column.swift
  client-mobile/ToDoListApp/ToDoListApp/ViewControllers/ColumnViewController.swift
  client-mobile/ToDoListApp/ToDoListApp/ViewModels/CardListViewModel.swift
  client-mobile/ToDoListApp/ToDoListApp/ViewModels/ColumnViewModel.swift
  client-mobile/ToDoListApp/ToDoListApp/Views/CardList/BadgeView.swift
  client-mobile/ToDoListApp/ToDoListApp/Views/CardList/CardListDataSource.swift
  client-mobile/ToDoListApp/ToDoListApp/Views/CardList/ColumnView.swift
Labels: iOS, refactoring

#68 [FE] 드래그앤드랍 리팩토링 & 기능 추가
  FE/src/js/components/Column.js
  FE/src/js/components/ColumnContainer.js
Labels: FE

#70 로그인, 인터셉터 기능 추가
  .idea/.gitignore
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/todo-1.iml
  .idea/vcs.xml
  .idea/workspace.xml
  BE/.gitignore
  BE/build.gradle
  BE/src/main/java/com/codesquad/todo1/api/ApiCard.java
  BE/src/main/java/com/codesquad/todo1/api/ApiLogin.java
  BE/src/main/java/com/codesquad/todo1/api/ApiShowList.java
  BE/src/main/java/com/codesquad/todo1/config/WebConfig.java
  BE/src/main/java/com/codesquad/todo1/controller/LoginController.java
  BE/src/main/java/com/codesquad/todo1/controller/TodoController.java
  BE/src/main/java/com/codesquad/todo1/domain/User.java
  BE/src/main/java/com/codesquad/todo1/error/AuthorizationFail.java
  BE/src/main/java/com/codesquad/todo1/repository/CategoryRepository.java
  BE/src/main/java/com/codesquad/todo1/repository/UserRepository.java
  BE/src/main/java/com/codesquad/todo1/service/TodoService.java
  BE/src/main/java/com/codesquad/todo1/utils/JwtUtils.java
  BE/src/main/java/com/codesquad/todo1/utils/LoginInterceptor.java
  BE/src/main/resources/application.properties
  BE/src/main/resources/schema.sql
Labels: BE

#73 [FE] Activity 애니메이션 구현
  FE/src/js/activityData.js
  FE/src/js/components/Activity.js
  FE/src/js/components/CardCreator.js
  FE/src/js/components/ColumnContainer.js
  FE/src/js/components/Header.js
  FE/src/js/components/History.js
  FE/src/js/utils/template.js
  FE/src/scss/pages/todo.scss
  FE/src/scss/partials/activity.scss
  FE/src/scss/styles.scss
Labels: FE

#76 [Bugfix] 로그인 진행 후 Cors문제 해결
  BE/src/main/java/com/codesquad/todo1/config/WebConfig.java
Labels: BE, bug

#78 카드 업데이트 기능 추가
  BE/src/main/java/com/codesquad/todo1/api/ApiLogin.java
  BE/src/main/java/com/codesquad/todo1/controller/LoginController.java
  BE/src/main/java/com/codesquad/todo1/controller/TodoController.java
  BE/src/main/java/com/codesquad/todo1/domain/Card.java
  BE/src/main/java/com/codesquad/todo1/domain/Category.java
  BE/src/main/java/com/codesquad/todo1/error/AuthorizationFail.java
  BE/src/main/java/com/codesquad/todo1/error/FindCategoryFail.java
  BE/src/main/java/com/codesquad/todo1/error/UpdateCardFail.java
  BE/src/main/java/com/codesquad/todo1/service/TodoService.java
  BE/src/main/resources/data.sql
Labels: BE

#89 로그인 기능 구현
  client-mobile/ToDoListApp/ToDoListApp.xcodeproj/project.pbxproj
  client-mobile/ToDoListApp/ToDoListApp/AppDelegate.swift
  client-mobile/ToDoListApp/ToDoListApp/Assets.xcassets/LogInBG2.imageset/Contents.json
  client-mobile/ToDoListApp/ToDoListApp/Assets.xcassets/LogInBG2.imageset/LogInBG2.jpeg
  client-mobile/ToDoListApp/ToDoListApp/Assets.xcassets/LogInButtonColor.colorset/Contents.json
  client-mobile/ToDoListApp/ToDoListApp/Assets.xcassets/line.horizontal.3.symbolset/Contents.json
  client-mobile/ToDoListApp/ToDoListApp/Assets.xcassets/line.horizontal.3.symbolset/line.horizontal.3.svg
  client-mobile/ToDoListApp/ToDoListApp/Assets.xcassets/person.crop.circle.fill.symbolset/Contents.json
  client-mobile/ToDoListApp/ToDoListApp/Assets.xcassets/person.crop.circle.fill.symbolset/person.crop.circle.fill.svg
  client-mobile/ToDoListApp/ToDoListApp/Assets.xcassets/person.crop.circle.symbolset/Contents.json
  client-mobile/ToDoListApp/ToDoListApp/Assets.xcassets/person.crop.circle.symbolset/person.crop.circle.svg
  client-mobile/ToDoListApp/ToDoListApp/Base.lproj/Main.storyboard
  client-mobile/ToDoListApp/ToDoListApp/Models/LogIn/TokenManager.swift
  client-mobile/ToDoListApp/ToDoListApp/Models/LogIn/User.swift
  client-mobile/ToDoListApp/ToDoListApp/Models/NetworkManager.swift
  client-mobile/ToDoListApp/ToDoListApp/Models/UserData.swift
  client-mobile/ToDoListApp/ToDoListApp/ViewControllers/HomeViewController.swift
  client-mobile/ToDoListApp/ToDoListApp/ViewControllers/LogInViewController.swift
  client-mobile/ToDoListApp/ToDoListApp/ViewControllers/ToDoListViewController.swift
  client-mobile/ToDoListApp/ToDoListApp/ViewControllers/UserInfoViewController.swift
  client-mobile/ToDoListApp/ToDoListApp/Views/LogIn/LogInTextField.swift
Labels: enhancement, iOS

#91 Be/feature/movcard
  BE/src/main/java/com/codesquad/todo1/api/ApiCard.java
  BE/src/main/java/com/codesquad/todo1/controller/LoginController.java
  BE/src/main/java/com/codesquad/todo1/controller/TodoController.java
  BE/src/main/java/com/codesquad/todo1/domain/Card.java
  BE/src/main/java/com/codesquad/todo1/domain/Category.java
  BE/src/main/java/com/codesquad/todo1/repository/CategoryRepository.java
  BE/src/main/java/com/codesquad/todo1/repository/UserRepository.java
  BE/src/main/java/com/codesquad/todo1/service/TodoService.java
  BE/src/main/resources/application.properties
  BE/src/main/resources/data.sql
Labels: BE

#93 [#92] bugfix: Cors Access-Control-Allow-Origin 헤더설정
  BE/src/main/java/com/codesquad/todo1/config/SimpleCorsFilter.java
  BE/src/main/java/com/codesquad/todo1/domain/Category.java
  BE/src/main/java/com/codesquad/todo1/service/TodoService.java
Labels: BE, bug

#97 [#92] bugfix : Cors Options메서드만 jwt통과
  BE/src/main/java/com/codesquad/todo1/utils/LoginInterceptor.java
Labels: BE, bug

#98 서버 응답 기반으로 카드 추가 구현
  client-mobile/ToDoListApp/ToDoListApp.xcodeproj/project.pbxproj
  client-mobile/ToDoListApp/ToDoListApp/Models/CardList/CardContainer.swift
  client-mobile/ToDoListApp/ToDoListApp/Models/CardList/NewCardRequest.swift
  client-mobile/ToDoListApp/ToDoListApp/Models/LogIn/TokenManager.swift
  client-mobile/ToDoListApp/ToDoListApp/Models/NetworkManager.swift
  client-mobile/ToDoListApp/ToDoListApp/ViewControllers/ColumnViewController.swift
  client-mobile/ToDoListApp/ToDoListApp/ViewControllers/HomeViewController.swift
  client-mobile/ToDoListApp/ToDoListApp/ViewControllers/NewCardViewController.swift
Labels: enhancement, iOS

#100 [#92] Cors PUT, PATCH 메서드 추가
  BE/src/main/java/com/codesquad/todo1/config/SimpleCorsFilter.java
Labels: BE, bug

#104 [FE] 서버 연동 완료
  FE/config/webpack.config.dev.js
  FE/config/webpack.config.prod.js
  FE/src/js/components/Activity.js
  FE/src/js/components/CardCreator.js
  FE/src/js/components/Column.js
  FE/src/js/components/ColumnContainer.js
  FE/src/js/components/Header.js
  FE/src/js/login.js
  FE/src/js/todo.js
  FE/src/js/utils/HttpRequestHandler.js
  FE/src/js/utils/const.js
  FE/src/js/utils/template.js
  FE/src/js/utils/utilFunction.js
Labels: FE

#105 [#99] Bugfix : 카드 생성 시 역순으로 추가 기능으로 변경
  BE/src/main/java/com/codesquad/todo1/api/ApiLogin.java
  BE/src/main/java/com/codesquad/todo1/controller/LoginController.java
  BE/src/main/java/com/codesquad/todo1/controller/TodoController.java
  BE/src/main/java/com/codesquad/todo1/domain/Category.java
  BE/src/main/java/com/codesquad/todo1/domain/User.java
  BE/src/main/java/com/codesquad/todo1/service/TodoService.java
  BE/src/main/java/com/codesquad/todo1/utils/LoginInterceptor.java
  BE/src/main/resources/data.sql
  BE/src/main/resources/schema.sql
Labels: BE, bug

#110 [BE] 유저 정보 출력 기능 추가 및 데이터 정보 시간
  BE/src/main/java/com/codesquad/todo1/api/ApiUserInfo.java
  BE/src/main/java/com/codesquad/todo1/controller/HistoryController.java
  BE/src/main/java/com/codesquad/todo1/controller/LoginController.java
  BE/src/main/java/com/codesquad/todo1/domain/Card.java
  BE/src/main/java/com/codesquad/todo1/domain/Category.java
  BE/src/main/java/com/codesquad/todo1/domain/History.java
  BE/src/main/java/com/codesquad/todo1/repository/CategoryRepository.java
  BE/src/main/java/com/codesquad/todo1/repository/HistoryRepository.java
  BE/src/main/java/com/codesquad/todo1/service/TodoService.java
  BE/src/main/java/com/codesquad/todo1/service/UserService.java
  BE/src/main/java/com/codesquad/todo1/utils/LoginInterceptor.java
  BE/src/main/resources/application.properties
  BE/src/main/resources/data.sql
  BE/src/main/resources/schema.sql
Labels: BE

#115 로그아웃 기능 & 사용자 정보 통신 및 업데이트
  client-mobile/ToDoListApp/ToDoListApp.xcodeproj/project.pbxproj
  client-mobile/ToDoListApp/ToDoListApp/AppDelegate.swift
  client-mobile/ToDoListApp/ToDoListApp/Base.lproj/Main.storyboard
  client-mobile/ToDoListApp/ToDoListApp/Extensions/StackView+Extension.swift
  client-mobile/ToDoListApp/ToDoListApp/Models/LogIn/TokenManager.swift
  client-mobile/ToDoListApp/ToDoListApp/Models/LogIn/UserInfo.swift
  client-mobile/ToDoListApp/ToDoListApp/Models/NetworkManager.swift
  client-mobile/ToDoListApp/ToDoListApp/ViewControllers/HomeViewController.swift
  client-mobile/ToDoListApp/ToDoListApp/ViewControllers/UserInfoViewController.swift
Labels: enhancement, iOS

#118 bugfix: 카드 추가, 업데이트 수정
  BE/src/main/java/com/codesquad/todo1/api/ApiUserInfo.java
  BE/src/main/java/com/codesquad/todo1/controller/LoginController.java
  BE/src/main/java/com/codesquad/todo1/service/TodoService.java
  BE/src/main/resources/application.properties
Labels: BE, bug

#119 bugfix: 카드 추가, 업데이트
  BE/src/main/java/com/codesquad/todo1/api/ApiUserInfo.java
  BE/src/main/java/com/codesquad/todo1/controller/LoginController.java
  BE/src/main/java/com/codesquad/todo1/service/TodoService.java
  BE/src/main/resources/application.properties
Labels: BE, bug

#120 Context Menu를 통한 카드 수정 및 삭제
  client-mobile/ToDoListApp/ToDoListApp.xcodeproj/project.pbxproj
  client-mobile/ToDoListApp/ToDoListApp/Assets.xcassets/card-edit.symbolset/Contents.json
  client-mobile/ToDoListApp/ToDoListApp/Assets.xcassets/card-edit.symbolset/pencil.svg
  client-mobile/ToDoListApp/ToDoListApp/Assets.xcassets/card-remove.symbolset/Contents.json
  client-mobile/ToDoListApp/ToDoListApp/Assets.xcassets/card-remove.symbolset/trash.fill.svg
  client-mobile/ToDoListApp/ToDoListApp/Base.lproj/Main.storyboard
  client-mobile/ToDoListApp/ToDoListApp/ViewControllers/CardEditorViewController.swift
  client-mobile/ToDoListApp/ToDoListApp/ViewControllers/ColumnViewController.swift
  client-mobile/ToDoListApp/ToDoListApp/ViewControllers/HomeViewController.swift
  client-mobile/ToDoListApp/ToDoListApp/ViewModels/CardListViewModel.swift
  client-mobile/ToDoListApp/ToDoListApp/Views/NewCard/CardTitleTextFieldDelegate.swift
Labels: enhancement, iOS

#121 [FE] 리팩토링 완료
  FE/src/js/activityData.js
  FE/src/js/components/CardCreator.js
  FE/src/js/components/CardEditor.js
  FE/src/js/components/Column.js
  FE/src/js/components/ColumnContainer.js
  FE/src/js/components/ColumnCreator.js
  FE/src/js/components/Header.js
  FE/src/js/data.js
  FE/src/js/utils/const.js
  FE/src/js/utils/template.js
  FE/src/scss/pages/todo.scss
Labels: FE

#122 [BE] 리팩토링 및 예외처리 그리고 Activity 설정 수정
  BE/src/main/java/com/codesquad/todo1/api/ApiHistory.java
  BE/src/main/java/com/codesquad/todo1/api/ApiUserInfo.java
  BE/src/main/java/com/codesquad/todo1/controller/HistoryController.java
  BE/src/main/java/com/codesquad/todo1/controller/LoginController.java
  BE/src/main/java/com/codesquad/todo1/controller/TodoController.java
  BE/src/main/java/com/codesquad/todo1/domain/History.java
  BE/src/main/java/com/codesquad/todo1/service/HistoryService.java
  BE/src/main/java/com/codesquad/todo1/service/TodoService.java
  BE/src/main/java/com/codesquad/todo1/service/UserService.java
Labels: BE, bug

#124 카드 수정, 삭제 네트워크 요청 후 반영
  client-mobile/ToDoListApp/ToDoListApp/Models/CardList/Card.swift
  client-mobile/ToDoListApp/ToDoListApp/Models/NetworkManager.swift
  client-mobile/ToDoListApp/ToDoListApp/ViewControllers/CardEditorViewController.swift
  client-mobile/ToDoListApp/ToDoListApp/ViewControllers/ColumnViewController.swift
  client-mobile/ToDoListApp/ToDoListApp/ViewModels/CardListViewModel.swift
Labels: enhancement, iOS

#126 카드 추가 오류 해결
  client-mobile/ToDoListApp/ToDoListApp/ViewControllers/ColumnViewController.swift
Labels: hotfix, iOS

#129 카드 드래그 & 드롭 구현
  client-mobile/ToDoListApp/ToDoListApp.xcodeproj/project.pbxproj
  client-mobile/ToDoListApp/ToDoListApp/Models/CardList/CardMoveRequest.swift
  client-mobile/ToDoListApp/ToDoListApp/Models/CardList/DragCardCell.swift
  client-mobile/ToDoListApp/ToDoListApp/Models/User/User.swift
  client-mobile/ToDoListApp/ToDoListApp/Models/User/UserData.swift
  client-mobile/ToDoListApp/ToDoListApp/Models/User/UserInfo.swift
  client-mobile/ToDoListApp/ToDoListApp/Network/NetworkManager.swift
  client-mobile/ToDoListApp/ToDoListApp/Network/TokenManager.swift
  client-mobile/ToDoListApp/ToDoListApp/ViewControllers/Card/CardEditorViewController.swift
  client-mobile/ToDoListApp/ToDoListApp/ViewControllers/Column/ColumnViewController.swift
  client-mobile/ToDoListApp/ToDoListApp/ViewControllers/User/LogInViewController.swift
  client-mobile/ToDoListApp/ToDoListApp/ViewControllers/User/UserInfoViewController.swift
  client-mobile/ToDoListApp/ToDoListApp/ViewModels/AppDelegate.swift
  client-mobile/ToDoListApp/ToDoListApp/ViewModels/ColumnCardList/CardListViewModel.swift
  client-mobile/ToDoListApp/ToDoListApp/ViewModels/ColumnCardList/ColumnViewModel+DragDelegate.swift
  client-mobile/ToDoListApp/ToDoListApp/ViewModels/ColumnCardList/ColumnViewModel+DropDelegate.swift
  client-mobile/ToDoListApp/ToDoListApp/ViewModels/ColumnCardList/ColumnViewModel.swift
  client-mobile/ToDoListApp/ToDoListApp/ViewModels/SceneDelegate.swift
Labels: enhancement, iOS

#133 Be/bugfix/activity
  BE/src/main/java/com/codesquad/todo1/repository/HistoryRepository.java
  BE/src/main/java/com/codesquad/todo1/service/HistoryService.java
Labels: BE, bug

#134 [#132] Bugfix: Activity 유저 가리지 않고 전부 출력
  BE/src/main/java/com/codesquad/todo1/repository/HistoryRepository.java
  BE/src/main/java/com/codesquad/todo1/service/HistoryService.java
Labels: BE, bug

#136 [#135] Bugfix: 유저에 따른 history 기록 기능 구현
  BE/src/main/java/com/codesquad/todo1/controller/HistoryController.java
  BE/src/main/java/com/codesquad/todo1/controller/TodoController.java
  BE/src/main/java/com/codesquad/todo1/repository/HistoryRepository.java
  BE/src/main/java/com/codesquad/todo1/service/HistoryService.java
  BE/src/main/java/com/codesquad/todo1/service/TodoService.java
Labels: BE, bug

#137 [#135] Bugfix: 유저에 따른 history 기록 기능 구현
  BE/src/main/java/com/codesquad/todo1/controller/HistoryController.java
  BE/src/main/java/com/codesquad/todo1/controller/TodoController.java
  BE/src/main/java/com/codesquad/todo1/repository/HistoryRepository.java
  BE/src/main/java/com/codesquad/todo1/service/HistoryService.java
  BE/src/main/java/com/codesquad/todo1/service/TodoService.java
Labels: BE, bug

#138 [FE] 2주차 작업본 배포 준비 완료
  FE/build/login.bundle.js
  FE/build/login.html
  FE/build/style.css
  FE/build/todo.bundle.js
  FE/build/todo.html
  FE/config/webpack.config.dev.js
  FE/config/webpack.config.prod.js
  FE/package.json
  FE/src/js/components/Activity.js
  FE/src/js/components/CardCreator.js
  FE/src/js/components/CardEditor.js
  FE/src/js/components/Column.js
  FE/src/js/components/ColumnContainer.js
  FE/src/js/components/ColumnCreator.js
  FE/src/js/components/Header.js
  FE/src/js/components/History.js
  FE/src/js/data.js
  FE/src/js/login.js
  FE/src/js/login.ts
  FE/src/js/todo.js
  FE/src/js/todo.ts
  FE/src/js/utils/HttpRequestHandler.ts
  FE/src/js/utils/const.ts
  FE/src/js/utils/template.js
  FE/src/js/utils/template.ts
  FE/src/js/utils/utilFunction.ts
  FE/src/scss/config/reset.scss
  FE/src/scss/main.scss
  FE/src/scss/pages/todo.scss
  FE/src/scss/partials/activity.scss
  FE/src/scss/partials/cardEditor.scss
  FE/src/scss/styles.scss
  FE/tsconfig.json
Labels: FE

#139 Activity TableViewController 구현
  client-mobile/ToDoListApp/ToDoListApp.xcodeproj/project.pbxproj
  client-mobile/ToDoListApp/ToDoListApp/Base.lproj/Main.storyboard
  client-mobile/ToDoListApp/ToDoListApp/Models/Activity/Activity.swift
  client-mobile/ToDoListApp/ToDoListApp/Models/Activity/ActivityContainer.swift
  client-mobile/ToDoListApp/ToDoListApp/Network/NetworkManager.swift
  client-mobile/ToDoListApp/ToDoListApp/ViewControllers/Activity/ActivityViewController.swift
  client-mobile/ToDoListApp/ToDoListApp/ViewModels/ColumnCardList/CardListDataSource.swift
  client-mobile/ToDoListApp/ToDoListApp/ViewModels/Delegates/AppDelegate.swift
  client-mobile/ToDoListApp/ToDoListApp/ViewModels/Delegates/SceneDelegate.swift
  client-mobile/ToDoListApp/ToDoListApp/ViewModels/NewCard/CardContentsTextViewDelegate.swift
  client-mobile/ToDoListApp/ToDoListApp/ViewModels/NewCard/CardTitleTextFieldDelegate.swift
  client-mobile/ToDoListApp/ToDoListApp/Views/Activity/ActivityCell.swift
Labels: enhancement, iOS

#140 최종 데모데이
  client-mobile/ToDoListApp/ToDoListApp.xcodeproj/project.pbxproj
  client-mobile/ToDoListApp/ToDoListApp/Assets.xcassets/LogInBG2.imageset/Contents.json
  client-mobile/ToDoListApp/ToDoListApp/Assets.xcassets/LogInBG2.imageset/LogInBG2.jpeg
  client-mobile/ToDoListApp/ToDoListApp/Assets.xcassets/LogInButtonColor.colorset/Contents.json
  client-mobile/ToDoListApp/ToDoListApp/Assets.xcassets/card-edit.symbolset/Contents.json
  client-mobile/ToDoListApp/ToDoListApp/Assets.xcassets/card-edit.symbolset/pencil.svg
  client-mobile/ToDoListApp/ToDoListApp/Assets.xcassets/card-remove.symbolset/Contents.json
  client-mobile/ToDoListApp/ToDoListApp/Assets.xcassets/card-remove.symbolset/trash.fill.svg
  client-mobile/ToDoListApp/ToDoListApp/Assets.xcassets/line.horizontal.3.symbolset/Contents.json
  client-mobile/ToDoListApp/ToDoListApp/Assets.xcassets/line.horizontal.3.symbolset/line.horizontal.3.svg
  client-mobile/ToDoListApp/ToDoListApp/Assets.xcassets/person.crop.circle.fill.symbolset/Contents.json
  client-mobile/ToDoListApp/ToDoListApp/Assets.xcassets/person.crop.circle.fill.symbolset/person.crop.circle.fill.svg
  client-mobile/ToDoListApp/ToDoListApp/Assets.xcassets/person.crop.circle.symbolset/Contents.json
  client-mobile/ToDoListApp/ToDoListApp/Assets.xcassets/person.crop.circle.symbolset/person.crop.circle.svg
  client-mobile/ToDoListApp/ToDoListApp/Base.lproj/Main.storyboard
  client-mobile/ToDoListApp/ToDoListApp/Extensions/StackView+Extension.swift
  client-mobile/ToDoListApp/ToDoListApp/Models/Activity/Activity.swift
  client-mobile/ToDoListApp/ToDoListApp/Models/Activity/ActivityContainer.swift
  client-mobile/ToDoListApp/ToDoListApp/Models/CardList/Card.swift
  client-mobile/ToDoListApp/ToDoListApp/Models/CardList/CardContainer.swift
  client-mobile/ToDoListApp/ToDoListApp/Models/CardList/CardMoveRequest.swift
  client-mobile/ToDoListApp/ToDoListApp/Models/CardList/Column.swift
  client-mobile/ToDoListApp/ToDoListApp/Models/CardList/DragCardCell.swift
  client-mobile/ToDoListApp/ToDoListApp/Models/CardList/NewCardRequest.swift
  client-mobile/ToDoListApp/ToDoListApp/Models/NetworkManager.swift
  client-mobile/ToDoListApp/ToDoListApp/Models/User/User.swift
  client-mobile/ToDoListApp/ToDoListApp/Models/User/UserData.swift
  client-mobile/ToDoListApp/ToDoListApp/Models/User/UserInfo.swift
  client-mobile/ToDoListApp/ToDoListApp/Network/NetworkManager.swift
  client-mobile/ToDoListApp/ToDoListApp/Network/TokenManager.swift
  client-mobile/ToDoListApp/ToDoListApp/ViewControllers/Activity/ActivityViewController.swift
  client-mobile/ToDoListApp/ToDoListApp/ViewControllers/Card/CardEditorViewController.swift
  client-mobile/ToDoListApp/ToDoListApp/ViewControllers/Column/ColumnViewController.swift
  client-mobile/ToDoListApp/ToDoListApp/ViewControllers/ColumnViewController.swift
  client-mobile/ToDoListApp/ToDoListApp/ViewControllers/HomeViewController.swift
  client-mobile/ToDoListApp/ToDoListApp/ViewControllers/NewCardViewController.swift
  client-mobile/ToDoListApp/ToDoListApp/ViewControllers/ToDoListViewController.swift
  client-mobile/ToDoListApp/ToDoListApp/ViewControllers/User/LogInViewController.swift
  client-mobile/ToDoListApp/ToDoListApp/ViewControllers/User/UserInfoViewController.swift
  client-mobile/ToDoListApp/ToDoListApp/ViewModels/ColumnCardList/CardListDataSource.swift
  client-mobile/ToDoListApp/ToDoListApp/ViewModels/ColumnCardList/CardListViewModel.swift
  client-mobile/ToDoListApp/ToDoListApp/ViewModels/ColumnCardList/ColumnViewModel+DragDelegate.swift
  client-mobile/ToDoListApp/ToDoListApp/ViewModels/ColumnCardList/ColumnViewModel+DropDelegate.swift
  client-mobile/ToDoListApp/ToDoListApp/ViewModels/ColumnCardList/ColumnViewModel.swift
  client-mobile/ToDoListApp/ToDoListApp/ViewModels/Delegates/AppDelegate.swift
  client-mobile/ToDoListApp/ToDoListApp/ViewModels/Delegates/SceneDelegate.swift
  client-mobile/ToDoListApp/ToDoListApp/ViewModels/NewCard/CardContentsTextViewDelegate.swift
  client-mobile/ToDoListApp/ToDoListApp/ViewModels/NewCard/CardTitleTextFieldDelegate.swift
  client-mobile/ToDoListApp/ToDoListApp/ViewModels/NewCard/TitleViewModel.swift
  client-mobile/ToDoListApp/ToDoListApp/Views/Activity/ActivityCell.swift
  client-mobile/ToDoListApp/ToDoListApp/Views/CardList/BadgeView.swift
  client-mobile/ToDoListApp/ToDoListApp/Views/CardList/CardListDelegate.swift
  client-mobile/ToDoListApp/ToDoListApp/Views/CardList/ColumnView.swift
  client-mobile/ToDoListApp/ToDoListApp/Views/LogIn/LogInTextField.swift
Labels: enhancement, iOS

#141 README 업데이트
  client-mobile/README.md
  client-mobile/images/Columns-Process.jpeg
  client-mobile/images/Log-In-Process.jpeg
Labels: documentation, iOS

#131 [BE] 코드리뷰 요청
  .idea/.gitignore
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/todo-1.iml
  .idea/vcs.xml
  .idea/workspace.xml
  BE/.gitignore
  BE/build.gradle
  BE/gradle/wrapper/gradle-wrapper.jar
  BE/gradle/wrapper/gradle-wrapper.properties
  BE/gradlew
  BE/gradlew.bat
  BE/settings.gradle
  BE/src/main/java/com/codesquad/todo1/TodoApplication.java
  BE/src/main/java/com/codesquad/todo1/api/ApiCard.java
  BE/src/main/java/com/codesquad/todo1/api/ApiLogin.java
  BE/src/main/java/com/codesquad/todo1/api/ApiShowList.java
  BE/src/main/java/com/codesquad/todo1/api/ApiStatus.java
  BE/src/main/java/com/codesquad/todo1/config/SimpleCorsFilter.java
  BE/src/main/java/com/codesquad/todo1/config/WebConfig.java
  BE/src/main/java/com/codesquad/todo1/controller/LoginController.java
  BE/src/main/java/com/codesquad/todo1/controller/TodoController.java
  BE/src/main/java/com/codesquad/todo1/domain/Card.java
  BE/src/main/java/com/codesquad/todo1/domain/Category.java
  BE/src/main/java/com/codesquad/todo1/domain/History.java
  BE/src/main/java/com/codesquad/todo1/domain/Project.java
  BE/src/main/java/com/codesquad/todo1/domain/User.java
  BE/src/main/java/com/codesquad/todo1/error/AuthorizationFail.java
  BE/src/main/java/com/codesquad/todo1/error/FindCategoryFail.java
  BE/src/main/java/com/codesquad/todo1/error/UpdateCardFail.java
  BE/src/main/java/com/codesquad/todo1/repository/CategoryRepository.java
  BE/src/main/java/com/codesquad/todo1/repository/HistoryRepository.java
  BE/src/main/java/com/codesquad/todo1/repository/UserRepository.java
  BE/src/main/java/com/codesquad/todo1/service/TodoService.java
  BE/src/main/java/com/codesquad/todo1/utils/JwtUtils.java
  BE/src/main/java/com/codesquad/todo1/utils/LoginInterceptor.java
  BE/src/main/resources/application.properties
  BE/src/main/resources/data.sql
  BE/src/main/resources/schema.sql
  README.md
Labels: be-review
